In [2]:
import numpy as np

print(zeros := np.zeros(10))
print(ones := np.ones(10))
print(full := np.full(10, 2))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2 2 2 2 2 2 2 2 2 2]


In [4]:
a = np.array([1, 2])
print(np.tile(a, 2))
print(np.repeat(a, 3))

[1 2 1 2]
[1 1 1 2 2 2]


In [5]:
print(xarr := np.arange(5))
print(*xarr)

[0 1 2 3 4]
0 1 2 3 4


In [8]:
# vector operation in numpy
print(zeros + ones)
print(np.concatenate((zeros, ones)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
